# Generated by Django 4.0.4 on 2023-07-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estelam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
