# Generated by Django 4.2.3 on 2023-08-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estelam', '0004_search_mat_p_code_search_mat_p_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='')),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='search_mat',
            name='self_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
