# Generated by Django 4.2.3 on 2023-08-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estelam', '0006_companies_remove_search_company_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_company',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
