# Generated by Django 4.2.3 on 2023-08-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estelam', '0007_search_company_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='search_company',
            new_name='AddCompany',
        ),
        migrations.RenameModel(
            old_name='search_mat',
            new_name='Materials',
        ),
    ]
